reCaptcha #comment complete
teamdigitale/padigitale2026.gov.it-site pull request #234
Opened 2021-11-25 14:11 UTC by emnlpstr

Add reCaptcha to message-update

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](CONTRIBUTING.md)
- [x] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

2021-11-25 14:20 UTC, lollomag approved these changes

2021-11-29 15:37 UTC, sebbalex requested changes
I expect `yarn.lock` file here, since there is an extra dependency in `package.json`

2021-11-29 15:37 UTC, sebbalex commented on src/components/modal/ModalMessage.jsx
> +            if (data.message.includes('already exists') || data.success == false) {
this is no longer needed, "already exists" could not be raised here.

2021-11-29 20:48 UTC, sebbalex commented on src/components/modal/ModalMessage.jsx
> +            if (data.success == false) {
```suggestion
            if (data.success === false) {
```

2021-12-01 08:33 UTC, sebbalex approved these changes

2021-12-01 08:46 UTC, merged