unsubscribe page
teamdigitale/padigitale2026.gov.it-site pull request #256
Opened 2021-12-15 10:55 UTC by emnlpstr

new page unsubscribe

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](CONTRIBUTING.md)
- [x] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

2021-12-15 11:00 UTC, lollomag approved these changes

2021-12-15 11:07 UTC, sebbalex requested changes
`address` and `uuid` are search parameters, we don't have `jwt` here.

2021-12-15 11:07 UTC, sebbalex commented on src/layouts/UnsubscribePage.jsx
> +  const jwt = params.get('jwt');
```suggestion
  const address = params.get('address');
  const uuid = params.get('uuid');
```

2021-12-15 11:07 UTC, sebbalex commented on src/layouts/UnsubscribePage.jsx
> +    }
```suggestion
```

2021-12-15 11:07 UTC, sebbalex commented on src/layouts/UnsubscribePage.jsx
> +    const { address, uuid } = jwt_decode(jwt);
```suggestion
```

2021-12-15 11:07 UTC, sebbalex commented on src/layouts/UnsubscribePage.jsx
> +      body: JSON.stringify({ jwt }),
```suggestion
```

2021-12-15 11:07 UTC, sebbalex commented on src/layouts/UnsubscribePage.jsx
> +  }, [apiUrl, jwt]);
```suggestion
  }, [apiUrl]);
```

2021-12-16 09:09 UTC, sebbalex approved these changes

2021-12-16 09:09 UTC, merged