input-validation fix and contents
teamdigitale/padigitale2026.gov.it-site pull request #274
Opened 2022-01-19 11:31 UTC by emnlpstr

fixed input validation on form and fixed content on "soluzione-standard" page

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](CONTRIBUTING.md)
- [x] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

2022-01-19 11:33 UTC, lollomag approved these changes

2022-01-20 11:22 UTC, sebbalex requested changes
I'd change the validation rules behind `enteType` and `ente` fields.
Using `/^\p{L}/u` would match any unicode Letter avoiding complexity.
More info [here](https://unicode.org/reports/tr18/#General_Category_Property)

2022-01-20 11:22 UTC, sebbalex commented on src/components/modal/ModalUpdates.jsx
> +                          value: /^[A-zÀ-ú ]*$/i,
```suggestion
                          value: /^\p{L}/u,
```

2022-01-20 11:22 UTC, sebbalex commented on src/components/modal/ModalUpdates.jsx
> +                        value: /^[A-zÀ-ú_.\- ]*$/i,
```suggestion
                        value: /^\p{L}/u,
```

2022-01-20 12:16 UTC, sebbalex commented on src/components/modal/ModalUpdates.jsx
> +                          value: /\p{L}/u,
```suggestion
                          value: /^\p{L}/u,
```

2022-01-20 13:36 UTC, sebbalex approved these changes

2022-01-20 13:37 UTC, merged