fix url pages
teamdigitale/padigitale2026.gov.it-site pull request #314
Opened 2022-02-25 14:46 UTC by emnlpstr

The url of pages **soluzione-stardand**, **soluzione-progetti** and **faq** are fixed to match the breadcrumb.

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](CONTRIBUTING.md)
- [x] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [x] Have you written new tests for your core changes, as applicable?
- [x] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

2022-02-28 18:48 UTC, sebbalex commented
Typing in FAQ search box it is allowed only one character
cc @emnlpstr

2022-03-04 15:06 UTC, sebbalex requested changes
The page `soluzione-progetti` must be named as its content title: `presentazione-progetti` (slug, links and so on)

2022-03-08 13:30 UTC, emnlpstr commented on src/layouts/SolutionProjects.jsx
> +                <a href="/come-funziona/soluzione-progetti">Presentazione progetti</a>
Fixed

2022-03-10 09:53 UTC, sebbalex approved these changes

2022-03-10 09:54 UTC, merged