Feat/update text misure
teamdigitale/padigitale2026.gov.it-site pull request #321
Opened 2022-03-16 15:41 UTC by lollomag

2022-03-16 15:43 UTC, emnlpstr approved these changes

2022-03-18 18:18 UTC, sebbalex requested changes

2022-03-18 18:18 UTC, sebbalex commented on src/components/AccordionButtonFull.jsx
> +  const [,] = useContext(GlobalStateContext);
```suggestion

```

2022-03-21 08:24 UTC, emnlpstr commented on src/components/AccordionButtonFull.jsx
> +  const [,] = useContext(GlobalStateContext);
I removed it

2022-03-21 14:35 UTC, sebbalex approved these changes

2022-03-21 14:35 UTC, merged