Feat/come partecipare
teamdigitale/padigitale2026.gov.it-site pull request #322
Opened 2022-03-16 16:52 UTC by Fladiir

Added page come-partecipare

2022-03-17 08:08 UTC, emnlpstr approved these changes

2022-03-18 18:28 UTC, sebbalex requested changes

2022-03-18 18:28 UTC, sebbalex commented on src/layouts/CreaProfiloPage.jsx
> +const { title: seoTitle, description: seoDescription } = seo.faqPage;
This is wrong here

2022-03-21 08:23 UTC, emnlpstr commented on src/layouts/CreaProfiloPage.jsx
> +const { title: seoTitle, description: seoDescription } = seo.faqPage;
fixed

2022-03-22 08:39 UTC, sebbalex requested changes

2022-03-22 08:39 UTC, sebbalex commented on src/components/hero/HeroHowToDo.jsx
> +  // };
```suggestion

```

2022-03-22 08:39 UTC, sebbalex commented on src/components/hero/HeroHowToDo.jsx
> +                    </div> */}
Remove please

2022-03-22 08:39 UTC, sebbalex commented on src/layouts/CreaProfiloPage.jsx
> +  // const handleChange = (event) => {
same here

2022-03-22 08:39 UTC, sebbalex commented on src/layouts/CreaProfiloPage.jsx
> +      {/* <HeroSupport title={faq.hero.title} subtitle={faq.hero.subtitle} /> */}
```suggestion

```

2022-03-22 08:39 UTC, sebbalex commented on src/layouts/come-fare/KeypointSection.jsx
> +            {/* <Row>
same

2022-03-22 08:39 UTC, sebbalex commented on src/layouts/come-fare/KeypointSection.jsx
> +          {/* <Row>
same

2022-03-22 08:39 UTC, sebbalex commented on src/layouts/come-fare/Keypoints.jsx
> +                    {/* <img className={classes.keypointImage} src={`/assets/come-fare/${listItem.image}`} alt="" /> */}
same

2022-03-22 08:55 UTC, emnlpstr commented on src/layouts/come-fare/Keypoints.jsx
> +                    {/* <img className={classes.keypointImage} src={`/assets/come-fare/${listItem.image}`} alt="" /> */}
I removed all the comments

2022-03-22 14:22 UTC, sebbalex commented on src/layouts/come-fare/KeypointSection.jsx
> +          /* className="pl-lg-2 pr-lg-2 pl-3 pr-3" */
```suggestion
```

2022-03-22 20:57 UTC, sebbalex approved these changes

2022-03-22 20:57 UTC, merged