added new FAQ
teamdigitale/padigitale2026.gov.it-site pull request #422
Opened 2022-06-01 08:39 UTC by emnlpstr

added new FAQ

## Checklist

- [x] I followed the indications in the [CONTRIBUTING](CONTRIBUTING.md)
- [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?
- [x] Ready for review! :rocket:

2022-06-07 12:14 UTC, bfabio requested changes

2022-06-07 12:14 UTC, bfabio commented on contents/faq-page/faq.yml
> +        content: Gentile Utente, grazie per averci contattato. Per gestire più Scuole contemporaneamente in qualità di rappresentante legale, è necessario:<br><br>1. completare la procedura di primo
```suggestion
        content: Sì. Per gestire più Scuole contemporaneamente in qualità di rappresentante legale, è necessario:<br><br>1. completare la procedura di primo accesso e attivare il profilo di una delle Scuole;<br>2. contattare l'assistenza mediante il modulo presente nella sezione "Supporto" dell'area riservata di PA digitale 2026, indicando nel messaggio i nomi, gli indirizzi PEC e il codice IPA delle ulteriori Scuole per le quali si richiede l'attivazione del profilo.
```

2022-06-07 12:29 UTC, emnlpstr commented on contents/faq-page/faq.yml
> +        content: Gentile Utente, grazie per averci contattato. Per gestire più Scuole contemporaneamente in qualità di rappresentante legale, è necessario:<br><br>1. completare la procedura di primo
I made it

2022-06-08 13:50 UTC, bfabio requested changes

2022-06-08 13:50 UTC, bfabio commented on contents/faq-page/faq.yml
> +      - title: Come inserire l'eventuale avanzo? l’importo è messo a bilancio vincolato?
```suggestion
      - title: Come inserire l'eventuale avanzo? L’importo è messo a bilancio vincolato?
```

2022-06-08 13:50 UTC, bfabio commented on contents/faq-page/faq.yml
> +        content: Si, è possibile accedere al finanziamento previsto dall'Avviso al fine di adottare una sola delle due piattaforme, SPID o CIE, qualora una di esse sia stata già adottata dall'ente co
```suggestion
        content: Sì, è possibile accedere al finanziamento previsto dall'Avviso al fine di adottare una sola delle due piattaforme, SPID o CIE, qualora una di esse sia stata già adottata dall'ente con protocollo SAML2, come specificato nell'Allegato 2.
```

2022-06-08 13:50 UTC, bfabio commented on contents/faq-page/faq.yml
> +        content: Si, è possibile accedere al finanziamento previsto dall'Avviso nel caso in cui il processo di adozione della piattaforma di identità digitale SPID/CIE sia stato avviato a decorrere d
```suggestion
        content: Sì, è possibile accedere al finanziamento previsto dall'Avviso nel caso in cui il processo di adozione della piattaforma di identità digitale SPID/CIE sia stato avviato a decorrere dal 1° febbraio 2020 con fondi propri.
```

2022-06-08 13:50 UTC, bfabio commented on contents/faq-page/faq.yml
> +        content: Si, è possibile accedere al finanziamento previsto dall'Avviso nel caso in cui l'attivazione dei servizi di incasso (pagoPA) sia stata realizzata dopo il 01 Aprile 2021 con risorse f
```suggestion
        content: Sì, è possibile accedere al finanziamento previsto dall'Avviso nel caso in cui l'attivazione dei servizi di incasso (pagoPA) sia stata realizzata dopo il 01 Aprile 2021 con risorse finanziarie proprie.
```

2022-06-08 13:50 UTC, bfabio commented on contents/faq-page/faq.yml
> +        content: Si, è possibile accedere al finanziamento previsto dall'Avviso nel caso in cui l'implementazione dei servizi digitali (appIO) sia stata realizzata a decorrere dal 01 Aprile 2021, con
```suggestion
        content: Sì, è possibile accedere al finanziamento previsto dall'Avviso nel caso in cui l'implementazione dei servizi digitali (appIO) sia stata realizzata a decorrere dal 01 Aprile 2021, con risorse finanziarie proprie.
```

2022-06-08 13:50 UTC, bfabio commented on contents/faq-page/faq.yml
> +        content: Si, l'Avviso destina il 40% delle risorse al finanziamento di Soggetti Attuatori ubicati nelle regioni Abruzzo, Basilicata, Campania, Calabria, Molise, Puglia, Sardegna, Sicilia, nel
```suggestion
        content: Sì, l'Avviso destina il 40% delle risorse al finanziamento di Soggetti Attuatori ubicati nelle regioni Abruzzo, Basilicata, Campania, Calabria, Molise, Puglia, Sardegna, Sicilia, nel rispetto della priorità trasversale del PNRR relativa al “superamento dei divari territoriali” di cui all’art. 2 comma 6 bis del decreto- legge 31 maggio 2021 n.77, convertito in legge 29 luglio 2021, n. 108. 
```

2022-06-09 13:27 UTC, bfabio approved these changes

2022-06-09 13:28 UTC, merged