Patch 86
teamdigitale/padigitale2026.gov.it-site pull request #693
Opened 2023-07-20 08:04 UTC by dagdome

## Description

As already mentioned in #ISSUE_NUMBER, this PR tackles:
* ...
* ...
* ...

In particular, the ...

## Checklist

- [ ] I followed the indications in the [CONTRIBUTING](CONTRIBUTING.md)
- [ ] The documentation related to the proposed change has been updated accordingly (also comments in code).
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully ran tests with your changes locally?
- [ ] Ready for review! :rocket:

## Fixes

- Fixes #

2023-07-20 08:17 UTC, dagdome commented
please @westcoast

2023-07-20 12:08 UTC, westcoast requested changes
I Link a documentazione su GDrive devono essere aggiornati ai nuovi su SharePoint, GDrive è in dismissione a breve.
Suggerisco quindi di "rivedere" tutti i link presenti e aggiornarli al più presto, dato che GDrive andrà Off inizio settimana prossima.

2023-07-24 12:09 UTC, dagdome commented
a parte questo da te evidenziato non ci sono altri link da cambiare. possiamo procedere al caricamento della pull, grazie

2023-07-24 12:52 UTC, westcoast approved these changes

2023-07-24 12:53 UTC, westcoast approved these changes

2023-07-24 13:01 UTC, merged